// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: orphieData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrphieData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathVariable  string                 `protobuf:"bytes,1,opt,name=path_variable,json=pathVariable,proto3" json:"path_variable,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrphieData) Reset() {
	*x = OrphieData{}
	mi := &file_orphieData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphieData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphieData) ProtoMessage() {}

func (x *OrphieData) ProtoReflect() protoreflect.Message {
	mi := &file_orphieData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphieData.ProtoReflect.Descriptor instead.
func (*OrphieData) Descriptor() ([]byte, []int) {
	return file_orphieData_proto_rawDescGZIP(), []int{0}
}

func (x *OrphieData) GetPathVariable() string {
	if x != nil {
		return x.PathVariable
	}
	return ""
}

func (x *OrphieData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *OrphieData) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

type OrphieDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathVariable  string                 `protobuf:"bytes,1,opt,name=path_variable,json=pathVariable,proto3" json:"path_variable,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrphieDataResponse) Reset() {
	*x = OrphieDataResponse{}
	mi := &file_orphieData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphieDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphieDataResponse) ProtoMessage() {}

func (x *OrphieDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orphieData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphieDataResponse.ProtoReflect.Descriptor instead.
func (*OrphieDataResponse) Descriptor() ([]byte, []int) {
	return file_orphieData_proto_rawDescGZIP(), []int{1}
}

func (x *OrphieDataResponse) GetPathVariable() string {
	if x != nil {
		return x.PathVariable
	}
	return ""
}

func (x *OrphieDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *OrphieDataResponse) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

var File_orphieData_proto protoreflect.FileDescriptor

const file_orphieData_proto_rawDesc = "" +
	"\n" +
	"\x10orphieData.proto\x12\rorphieservice\x1a\x1bgoogle/protobuf/empty.proto\"b\n" +
	"\n" +
	"OrphieData\x12#\n" +
	"\rpath_variable\x18\x01 \x01(\tR\fpathVariable\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\"j\n" +
	"\x12OrphieDataResponse\x12#\n" +
	"\rpath_variable\x18\x01 \x01(\tR\fpathVariable\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType2\x9c\x01\n" +
	"\rOrphieService\x12L\n" +
	"\rGetOrphieData\x12\x16.google.protobuf.Empty\x1a!.orphieservice.OrphieDataResponse0\x01\x12=\n" +
	"\vHealthcheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x1cZ\x1agithub.com/Egot3/Orphie/pbb\x06proto3"

var (
	file_orphieData_proto_rawDescOnce sync.Once
	file_orphieData_proto_rawDescData []byte
)

func file_orphieData_proto_rawDescGZIP() []byte {
	file_orphieData_proto_rawDescOnce.Do(func() {
		file_orphieData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orphieData_proto_rawDesc), len(file_orphieData_proto_rawDesc)))
	})
	return file_orphieData_proto_rawDescData
}

var file_orphieData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orphieData_proto_goTypes = []any{
	(*OrphieData)(nil),         // 0: orphieservice.OrphieData
	(*OrphieDataResponse)(nil), // 1: orphieservice.OrphieDataResponse
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_orphieData_proto_depIdxs = []int32{
	2, // 0: orphieservice.OrphieService.GetOrphieData:input_type -> google.protobuf.Empty
	2, // 1: orphieservice.OrphieService.Healthcheck:input_type -> google.protobuf.Empty
	1, // 2: orphieservice.OrphieService.GetOrphieData:output_type -> orphieservice.OrphieDataResponse
	2, // 3: orphieservice.OrphieService.Healthcheck:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orphieData_proto_init() }
func file_orphieData_proto_init() {
	if File_orphieData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orphieData_proto_rawDesc), len(file_orphieData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orphieData_proto_goTypes,
		DependencyIndexes: file_orphieData_proto_depIdxs,
		MessageInfos:      file_orphieData_proto_msgTypes,
	}.Build()
	File_orphieData_proto = out.File
	file_orphieData_proto_goTypes = nil
	file_orphieData_proto_depIdxs = nil
}
