// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: orphieData.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrphieService_GetOrphieData_FullMethodName = "/orphieservice.OrphieService/GetOrphieData"
	OrphieService_Healthcheck_FullMethodName   = "/orphieservice.OrphieService/Healthcheck"
)

// OrphieServiceClient is the client API for OrphieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrphieServiceClient interface {
	GetOrphieData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrphieDataResponse], error)
	Healthcheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orphieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrphieServiceClient(cc grpc.ClientConnInterface) OrphieServiceClient {
	return &orphieServiceClient{cc}
}

func (c *orphieServiceClient) GetOrphieData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrphieDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrphieService_ServiceDesc.Streams[0], OrphieService_GetOrphieData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, OrphieDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrphieService_GetOrphieDataClient = grpc.ServerStreamingClient[OrphieDataResponse]

func (c *orphieServiceClient) Healthcheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrphieService_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrphieServiceServer is the server API for OrphieService service.
// All implementations must embed UnimplementedOrphieServiceServer
// for forward compatibility.
type OrphieServiceServer interface {
	GetOrphieData(*emptypb.Empty, grpc.ServerStreamingServer[OrphieDataResponse]) error
	Healthcheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrphieServiceServer()
}

// UnimplementedOrphieServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrphieServiceServer struct{}

func (UnimplementedOrphieServiceServer) GetOrphieData(*emptypb.Empty, grpc.ServerStreamingServer[OrphieDataResponse]) error {
	return status.Error(codes.Unimplemented, "method GetOrphieData not implemented")
}
func (UnimplementedOrphieServiceServer) Healthcheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedOrphieServiceServer) mustEmbedUnimplementedOrphieServiceServer() {}
func (UnimplementedOrphieServiceServer) testEmbeddedByValue()                       {}

// UnsafeOrphieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrphieServiceServer will
// result in compilation errors.
type UnsafeOrphieServiceServer interface {
	mustEmbedUnimplementedOrphieServiceServer()
}

func RegisterOrphieServiceServer(s grpc.ServiceRegistrar, srv OrphieServiceServer) {
	// If the following call panics, it indicates UnimplementedOrphieServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrphieService_ServiceDesc, srv)
}

func _OrphieService_GetOrphieData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrphieServiceServer).GetOrphieData(m, &grpc.GenericServerStream[emptypb.Empty, OrphieDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrphieService_GetOrphieDataServer = grpc.ServerStreamingServer[OrphieDataResponse]

func _OrphieService_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrphieServiceServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrphieService_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrphieServiceServer).Healthcheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OrphieService_ServiceDesc is the grpc.ServiceDesc for OrphieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrphieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orphieservice.OrphieService",
	HandlerType: (*OrphieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthcheck",
			Handler:    _OrphieService_Healthcheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrphieData",
			Handler:       _OrphieService_GetOrphieData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orphieData.proto",
}
